version: 1
runners:
  high:
    config-id: 3
jobs:
  build-prod:
    steps:
      - npm install -g zcatalyst-cli@beta
      - npm install
      - npm run build
      - rm -rf ./node_modules
      - npm install --omit=dev
      - catalyst deploy --org 870792532 --project 21874000000008212
stages:
  - name: deploy
    jobs:
        - build-prod