version: 1
pipeline-image: node:20
jobs:
  install-cli:
    steps:
      - echo "node -v"
      - echo "npm -v"
      - npm install -g zcatalyst-cli@beta
      - catalyst -v
  build:
    steps:
      - npm install
      - npm run setup
      - npm run build
  install-prod:
    artifacts:
      upload:
        - name: alien_city_build_<< env.BUILD_ID >>
          type: zip
          location: stratus://alien-city-prisma-development/build/artifacts
          regex:
            - '**/*'
    steps:
      - rm -rf ./node_modules
      - npm install --omit=dev
  catalyst-deploy:
    steps:
      - catalyst deploy --org 870792532 --project 21874000000008212
stages:
  - name: build
    jobs:
      - install-cli
      - build
      - install-prod
      - catalyst-deploy